version: "3"
services:
  ubuntu1:
    build : .
    container_name: ubuntu1
    stdin_open: true
    tty: true
    ports:
      - "2201:22"
    networks:
        - mynetwork
  ubuntu2:
    build : .
    container_name: ubuntu2
    stdin_open: true
    tty: true
    ports:
      - "2202:22"
    networks:
        - mynetwork
  ubuntu3:
    build : .
    container_name: ubuntu3
    stdin_open: true
    tty: true
    ports:
      - "2203:22"
    networks:
        - mynetwork


networks:
  mynetwork: 


